name: Build, Publish and Update

on:
  workflow_call:
    inputs:
      ACTOR:
        required: true
        type: string
      BRANCH_NAME:
        type: string
      NOTIFICATIONS_ENABLED:
        type: boolean
        required: false
        default: true
      GCRUN_SERVICE_NAME:
        required: true
        type: string
      GH_RUN_NUMBER:
        required: true
        type: string
      MIG_VERSION:
        required: false
        type: string
        default: 'a'
      PR_NUMBER:
        type: number
      REACT_APP_STAGE:
        type: string
        default: ''
      REPO:
        required: true
        type: string
      RUN_SONAR:
        type: boolean
        default: true
      SERVICE_NAME:
        required: true
        type: string
      SERVICE_TYPE:
        # Types:
        # [ cloud_run | mig ]
        type: string
        default: 'cloud_run'
      TAG_PREFIX:
        type: string
      TYPE:
        # Values:
        # [ preview | release | production ]
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_SA_GH_KEY:
        required: true
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SEMGREP_APP_TOKEN:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
      IMAGE_PATH: ${{ secrets.GCP_PROJECT_ID }}/${{ inputs.SERVICE_NAME }}
      MIG_NAME: events-${{ inputs.MIG_VERSION }}-mig
      PR_NUMBER: ${{ inputs.PR_NUMBER }}
      STAGE: ${{ inputs.REACT_APP_STAGE }}
    steps:
      - name: Starting notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ----------------------------------------------
            *${{ inputs.ACTOR }}* started:
            **${{ inputs.SERVICE_NAME }}** build *${{ inputs.GH_RUN_NUMBER }}*.
            URL: https://github.com/DeviantsFactions/${{ inputs.REPO }}/actions
            Type: *${{ inputs.TYPE }}*
            ----------------------------------------------
