name: Build, Publish and Update

on:
  workflow_call:
    inputs:
      ACTOR:
        required: true
        type: string
      BRANCH_NAME:
        type: string
      NOTIFICATIONS_ENABLED:
        type: boolean
        required: false
        default: true
      GCRUN_SERVICE_NAME:
        required: true
        type: string
      GH_RUN_NUMBER:
        required: true
        type: string
      MIG_VERSION:
        required: false
        type: string
        default: 'a'
      PR_NUMBER:
        type: number
      REACT_APP_STAGE:
        type: string
        default: ''
      REPO:
        required: true
        type: string
      RUN_SONAR:
        type: boolean
        default: true
      SERVICE_NAME:
        required: true
        type: string
      SERVICE_TYPE:
        # Types:
        # [ cloud_run | mig ]
        type: string
        default: 'cloud_run'
      TAG_PREFIX:
        type: string
      TYPE:
        # Values:
        # [ preview | release | production ]
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_SA_GH_KEY:
        required: true
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SEMGREP_APP_TOKEN:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Starting notification
        env:
          DISCORD_WEBHOOK: aaa
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ----------------------------------------------
            test
            ----------------------------------------------